# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 夏南瓜的小站
subtitle: ''
description: '记录学习中遇到的问题和思考'
keywords: Python, Emacs, Hexo, GitHub
author: 夏南瓜
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://blog.zucchiniy.com
permalink: posts/:abbrlink.html
abbrlink:
  alg: crc32
  rep: hex
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: volantis

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repo: git@github.com:ZucchiniY/hexo-blog.git
    branch: gh-pages
  # - type: cjh_google_url_submitter
  # - type: cjh_bing_url_submitter
  # - type: cjh_baidu_url_submitter

feed:
  enable: true
  type: atom
  path: atom.xml
  limit: false
  hub:
  content: true
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: https://cdn.jsdelivr.net/gh/Goopher97/tuchuang@master/img/%E7%8C%AB.png
  autodiscovery: true
  template:



# 站点地图
sitemap:
  path: sitemap.xml
  tag: true
  category: true
# 搜索引擎优化友好
nofollow:
  enable: true
  exclude:

# SEO
hexo_submit_urls_to_search_engine:
  submit_condition: count
  count: 10
  period: 900
  google: 1
  bing: 1
  baidu: 1
  txt_path: submit_urls.txt
  baidu_host: https://zucchiniy.cn
  baidu_token: 0
  bing_host: https://zucchiniy.cn
  bing_token: 0
  google_host: https://zucchiniy.cn
  google_key_file: Project.json
  replace: 0
  find_what: https://zucchiniy.cn
  replace_with: https://zucchiniy.cn

  
import:
  link:
    - <link rel="icon" type="image/png" sizes="32x32" href="https://cdn.jsdelivr.net/gh/zucchiniy/common@master/favicon/favicon-32x32.ico">
    - <link rel="icon" type="image/png" sizes="16x16" href="https://cdn.jsdelivr.net/gh/zucchiniy/common@master/favicon/favicon-16x16.ico">
    - <link rel="shortcut icon" href="https://cdn.jsdelivr.net/gh/zucchiniy/common@master/favicon/favicon.ico">
